### ISSUE TITLE
As an admin, I would like to be able to modify, add, or delete souvenirs from stadiums so that the program can be up to date.

### ISSUE THREAD

**Issue by xavierliancw** [xavierliancw/Based-Itinerary#17]
Overview:
- There is a table of souvenirs below the stadium listing on the admin page
- The table displays the souvenir, and its price
- Double clicking something in that table will make it editable
- There is a button that will pull up a new dialog to add a new souvenir
- That dialog has fields for souvenir name and for its price
- That dialog also has a save and cancel button
- Leaving either blank when attempting to save will make an error message pop up
- When a new souvenir is added, it is immediately reflected on the table of souvenirs on the admin page
- There is a delete button on the admin page that will delete a selected souvenir
- An error message pops up if there is no souvenir selected
- Requirement 2.9, 3.1, 3.2

Tasks:
- Requires stadium vector structure that holds all stadium information and souvenir information
- [x] Create a class method to add a new souvenir object
- [x] Create a class method to modify an existing souvenir object
- [x] Create a class method to delete an existing souvenir object
- [x] Create a table below the admin stadium listing to display souvenirs and their prices
- [x] Create a button that will delete a souvenir
- [x] Create a dialog class to handle adding a new souvenir
- [x] Create a button that will summon that new dialog
- [x] Create a fields in the dialog for name and price input
- [x] Create save and cancel buttons on the dialog
- [x] Create a refresh function that will refresh the souvenir table so that changes made can be immediately noticed (#93)
- [x] Link all GUI elements to the class methods created earlier
- [x] Error box for empty fields in the new souvenir window (#56)
- [x] Error box for invalid characters in price fields (#56)
- [x] Error box if stadium isn't selected when adding a new souvenir (#56)
- [x] Error box if no souvenir is selected when trying to delete

Definition of Done:
- [x] There is a table of souvenirs that displays a stadium's souvenirs when a stadium is selected
- [x] The table updates to display another stadium's souvenirs if another stadium is selected
- [x] An admin will be able to add a new souvenir to a stadium via a dialog window
- [x] Attempting to save with empty fields will generate an error message
- [x] Attempting to put in invalid characters into the price field will generate an error message
- [x] An admin will be able to modify an existing souvenir by double clicking a field in the table
- [x] Attempting to input invalid characters into the price field will generate an error
- [x] An admin will be able to delete a souvenir from a stadium
- [x] Attempting to delete a souvenir when there are none selected will generate an error

**Comment by xavierliancw** [comment]
One of your previous pr's have completed some of this stuff. I checked the boxes that have been completed for you.

**Comment by xavierliancw** [comment]
You really gotta error check for blank fields on your dialog for adding souvenirs. If you click ok/save with blank fields, the program crashes.
